// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from gmocktest.djinni

#pragma once

#include "djinni_support.hpp"
#include "turtle.hpp"

namespace djinni_generated {

class NativeTurtle final : ::djinni::JniInterface<::gmocktest::Turtle, NativeTurtle> {
public:
    using CppType = std::shared_ptr<::gmocktest::Turtle>;
    using JniType = jobject;

    using Boxed = NativeTurtle;

    ~NativeTurtle();

    static CppType toCpp(JNIEnv* jniEnv, JniType j) { return ::djinni::JniClass<NativeTurtle>::get()._fromJava(jniEnv, j); }
    static ::djinni::LocalRef<JniType> fromCpp(JNIEnv* jniEnv, const CppType& c) { return {jniEnv, ::djinni::JniClass<NativeTurtle>::get()._toJava(jniEnv, c)}; }

private:
    NativeTurtle();
    friend ::djinni::JniClass<NativeTurtle>;
    friend ::djinni::JniInterface<::gmocktest::Turtle, NativeTurtle>;

};

}  // namespace djinni_generated
