// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from gmocktest.djinni

#pragma once

#include "djinni_support.hpp"
#include "painter.hpp"

namespace djinni_generated {

class NativePainter final : ::djinni::JniInterface<::gmocktest::Painter, NativePainter> {
public:
    using CppType = std::shared_ptr<::gmocktest::Painter>;
    using JniType = jobject;

    using Boxed = NativePainter;

    ~NativePainter();

    static CppType toCpp(JNIEnv* jniEnv, JniType j) { return ::djinni::JniClass<NativePainter>::get()._fromJava(jniEnv, j); }
    static ::djinni::LocalRef<JniType> fromCpp(JNIEnv* jniEnv, const CppType& c) { return {jniEnv, ::djinni::JniClass<NativePainter>::get()._toJava(jniEnv, c)}; }

private:
    NativePainter();
    friend ::djinni::JniClass<NativePainter>;
    friend ::djinni::JniInterface<::gmocktest::Painter, NativePainter>;

};

}  // namespace djinni_generated
