// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from gmocktest.djinni

package com.mycompany.gmocktest;

import java.util.concurrent.atomic.AtomicBoolean;

public abstract class Painter {
    public abstract boolean drawCircle(int x, int y, int radius);

    public static native Painter createWithTurtle(Turtle turtle);

    private static final class CppProxy extends Painter
    {
        private final long nativeRef;
        private final AtomicBoolean destroyed = new AtomicBoolean(false);

        private CppProxy(long nativeRef)
        {
            if (nativeRef == 0) throw new RuntimeException("nativeRef is zero");
            this.nativeRef = nativeRef;
        }

        private native void nativeDestroy(long nativeRef);
        public void destroy()
        {
            boolean destroyed = this.destroyed.getAndSet(true);
            if (!destroyed) nativeDestroy(this.nativeRef);
        }
        protected void finalize() throws java.lang.Throwable
        {
            destroy();
            super.finalize();
        }

        @Override
        public boolean drawCircle(int x, int y, int radius)
        {
            assert !this.destroyed.get() : "trying to use a destroyed object";
            return native_drawCircle(this.nativeRef, x, y, radius);
        }
        private native boolean native_drawCircle(long _nativeRef, int x, int y, int radius);
    }
}
