// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from gmocktest.djinni

package com.mycompany.gmocktest;

import java.util.concurrent.atomic.AtomicBoolean;

public abstract class Turtle {
    public abstract void penDown();

    public static native Turtle create();

    private static final class CppProxy extends Turtle
    {
        private final long nativeRef;
        private final AtomicBoolean destroyed = new AtomicBoolean(false);

        private CppProxy(long nativeRef)
        {
            if (nativeRef == 0) throw new RuntimeException("nativeRef is zero");
            this.nativeRef = nativeRef;
        }

        private native void nativeDestroy(long nativeRef);
        public void destroy()
        {
            boolean destroyed = this.destroyed.getAndSet(true);
            if (!destroyed) nativeDestroy(this.nativeRef);
        }
        protected void finalize() throws java.lang.Throwable
        {
            destroy();
            super.finalize();
        }

        @Override
        public void penDown()
        {
            assert !this.destroyed.get() : "trying to use a destroyed object";
            native_penDown(this.nativeRef);
        }
        private native void native_penDown(long _nativeRef);
    }
}
