// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from gmocktest.djinni

#include "painter.hpp"
#include <memory>

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

@class GMTPainter;

namespace djinni_generated {

class Painter
{
public:
    using CppType = std::shared_ptr<::gmocktest::Painter>;
    using ObjcType = GMTPainter*;

    using Boxed = Painter;

    static CppType toCpp(ObjcType objc);
    static ObjcType fromCpp(const CppType& cpp);

private:
    class ObjcProxy;
};

}  // namespace djinni_generated

