// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from gmocktest.djinni

#import <Foundation/Foundation.h>
@class GMTPainter;
@class GMTTurtle;


@interface GMTPainter : NSObject

+ (nullable GMTPainter *)createWithTurtle:(nullable GMTTurtle *)turtle;

- (BOOL)drawCircle:(int32_t)x
                 y:(int32_t)y
            radius:(int32_t)radius;

@end
