// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from gmocktest.djinni

#import "GMTTurtle+Private.h"
#import "GMTTurtle.h"
#import "DJICppWrapperCache+Private.h"
#import "DJIError.h"
#import "GMTTurtle+Private.h"
#include <exception>
#include <utility>

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

@interface GMTTurtle ()

- (id)initWithCpp:(const std::shared_ptr<::gmocktest::Turtle>&)cppRef;

@end

@implementation GMTTurtle {
    ::djinni::CppProxyCache::Handle<std::shared_ptr<::gmocktest::Turtle>> _cppRefHandle;
}

- (id)initWithCpp:(const std::shared_ptr<::gmocktest::Turtle>&)cppRef
{
    if (self = [super init]) {
        _cppRefHandle.assign(cppRef);
    }
    return self;
}

+ (nullable GMTTurtle *)create {
    try {
        auto r = ::gmocktest::Turtle::create();
        return ::djinni_generated::Turtle::fromCpp(r);
    } DJINNI_TRANSLATE_EXCEPTIONS()
}

- (void)penDown {
    try {
        _cppRefHandle.get()->pen_down();
    } DJINNI_TRANSLATE_EXCEPTIONS()
}

namespace djinni_generated {

auto Turtle::toCpp(ObjcType objc) -> CppType
{
    if (!objc) {
        return nullptr;
    }
    return objc->_cppRefHandle.get();
}

auto Turtle::fromCpp(const CppType& cpp) -> ObjcType
{
    if (!cpp) {
        return nil;
    }
    return ::djinni::get_cpp_proxy<GMTTurtle>(cpp);
}

}  // namespace djinni_generated

@end
