// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from gmocktest.djinni

#import <Foundation/Foundation.h>
@class GMTTurtle;


@interface GMTTurtle : NSObject

+ (nullable GMTTurtle *)create;

- (void)penDown;

@end
