// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from gmocktest.djinni

#include "turtle.hpp"
#include <memory>

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

@class GMTTurtle;

namespace djinni_generated {

class Turtle
{
public:
    using CppType = std::shared_ptr<::gmocktest::Turtle>;
    using ObjcType = GMTTurtle*;

    using Boxed = Turtle;

    static CppType toCpp(ObjcType objc);
    static ObjcType fromCpp(const CppType& cpp);

private:
    class ObjcProxy;
};

}  // namespace djinni_generated

