// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from gmocktest.djinni

#pragma once

#include <cstdint>
#include <memory>

namespace gmocktest {

class Turtle;

class Painter {
public:
    virtual ~Painter() {}

    static std::shared_ptr<Painter> create_with_turtle(const std::shared_ptr<Turtle> & turtle);

    virtual bool draw_circle(int32_t x, int32_t y, int32_t radius) = 0;
};

}  // namespace gmocktest
