// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from gmocktest.djinni

#pragma once

#include <memory>

namespace gmocktest {

class Turtle {
public:
    virtual ~Turtle() {}

    static std::shared_ptr<Turtle> create();

    virtual void pen_down() = 0;
};

}  // namespace gmocktest
